/* EH! JADI GA? — mobile web data */

const UPCOMING_OPEN_TRIPS = [
  {
    id: "kelud-jun",
    dest: "Mt. Kelud",
    region: "Kediri, Jawa Timur",
    kind: "Open trip",
    emoji: "🌋",
    palette: "warm",
    start: "14 Jun",
    end: "15 Jun",
    month: "JUN",
    day: "14",
    duration: "2H1M",
    price: "485.000",
    slots: 6,
    totalSlots: 12,
    highlights: ["Sunrise di puncak", "Anak Gunung Kelud", "Bakso Kediri"],
    includes: ["Open trip shuttle dari Kediri", "Homestay 1 malam", "2x makan + 1x breakfast", "Guide lokal", "Retribusi + parkir", "P3K"],
    tag: "🔥 Populer",
  },
  {
    id: "pacitan-jun",
    dest: "Pacitan",
    region: "Pacitan, Jawa Timur",
    kind: "Open trip",
    emoji: "🏖️",
    palette: "sky",
    start: "21 Jun",
    end: "23 Jun",
    month: "JUN",
    day: "21",
    duration: "3H2M",
    price: "950.000",
    slots: 10,
    totalSlots: 12,
    highlights: ["Pantai Klayar", "Goa Gong", "Sunset Pantai Watu Karung"],
    includes: ["Transport Malang/Solo", "Homestay 2 malam", "5x makan", "Guide lokal", "Retribusi", "Snorkel gear"],
    tag: null,
  },
  {
    id: "kebo-jul",
    dest: "Pantai Kebo",
    region: "Trenggalek, Jawa Timur",
    kind: "Open trip",
    emoji: "🏝️",
    palette: "sky",
    start: "05 Jul",
    end: "06 Jul",
    month: "JUL",
    day: "05",
    duration: "2H1M",
    price: "575.000",
    slots: 3,
    totalSlots: 10,
    highlights: ["Pantai hidden gem", "Camping seaside", "Fresh seafood"],
    includes: ["Transport sharing", "Tent + sleeping gear", "Dinner BBQ + breakfast", "Guide", "Retribusi"],
    tag: "⚡ Hampir penuh",
  },
  {
    id: "pronojiwo-jul",
    dest: "Pronojiwo",
    region: "Lumajang, Jawa Timur",
    kind: "Open trip",
    emoji: "💧",
    palette: "forest",
    start: "19 Jul",
    end: "20 Jul",
    month: "JUL",
    day: "19",
    duration: "2H1M",
    price: "650.000",
    slots: 8,
    totalSlots: 12,
    highlights: ["Tumpak Sewu waterfall", "Goa Tetes", "Kapas Biru"],
    includes: ["Transport dari Malang", "Homestay", "3x makan", "Guide + body rafting gear", "Retribusi"],
    tag: null,
  },
  {
    id: "jurang-aug",
    dest: "Jurang Senggani",
    region: "Tulungagung, Jawa Timur",
    kind: "Open trip",
    emoji: "🏕️",
    palette: "forest",
    start: "02 Aug",
    end: "03 Aug",
    month: "AUG",
    day: "02",
    duration: "2H1M",
    price: "525.000",
    slots: 12,
    totalSlots: 12,
    highlights: ["Hutan pinus", "Sunrise campsite", "Air terjun tersembunyi"],
    includes: ["Shuttle + jeep", "Glamping tent (add-on)", "4x makan", "Guide + fire wood", "Retribusi"],
    tag: "✨ Baru dibuka",
  },
];

// Destinations available for Private trip configurator
const PRIVATE_DESTINATIONS = [
  { id: "pronojiwo", name: "Pronojiwo", sub: "Tumpak Sewu + Kapas Biru", emoji: "💧", palette: "forest" },
  { id: "pacitan",   name: "Pacitan",   sub: "Pantai + goa + pesisir selatan", emoji: "🏖️", palette: "sky" },
  { id: "kebo",      name: "Pantai Kebo", sub: "Hidden beach Trenggalek", emoji: "🏝️", palette: "sky" },
  { id: "jurang",    name: "Jurang Senggani", sub: "Hutan pinus + camp", emoji: "🌲", palette: "forest" },
  { id: "kelud",     name: "Mt. Kelud",  sub: "Sunrise + kawah aktif", emoji: "🌋", palette: "warm" },
  { id: "custom",    name: "Lainnya",    sub: "Request destinasi custom", emoji: "📍", palette: "" },
];

const GLAMPINGS = [
  {
    id: "jurang-senggani",
    name: "Jurang Senggani",
    location: "Tulungagung, Jawa Timur",
    emoji: "🌲",
    palette: "forest",
    price: "525.000",
    unit: "malam",
    cap: "2–4 orang",
    tagline: "Tent pinggir hutan pinus, api unggun tiap malam.",
    description: "Camping ground di kaki Gunung Wilis. Udara dingin, suara jangkrik, dan langit bintang yang jarang banget keliatan di kota. Cocok buat escape weekend sama pasangan atau grup kecil.",
    amenities: ["Tent dome + kasur", "Selimut + bantal", "Api unggun", "Toilet bersih", "Air hangat", "Snack box + kopi pagi"],
    availability: "Available · tiap weekend",
    tag: "🔥 Populer",
  },
  {
    id: "irrenggolo",
    name: "Irrenggolo Waterfalls",
    location: "Kediri, Jawa Timur",
    emoji: "💧",
    palette: "forest",
    price: "650.000",
    unit: "malam",
    cap: "2–5 orang",
    tagline: "Tenda di samping air terjun, 3 menit jalan kaki.",
    description: "Glamping di dekat Air Terjun Irrenggolo. Bangun pagi langsung suara air. Tenda teepee-style, ada dek outdoor buat kopi-kopi sore.",
    amenities: ["Teepee tent", "Dek outdoor", "Bathroom semi-outdoor", "Akses waterfall", "Breakfast hangat", "Free parking"],
    availability: "Book H-7",
    tag: "✨ Baru",
  },
  {
    id: "loji",
    name: "Hutan Pinus Loji",
    location: "Tulungagung, Jawa Timur",
    emoji: "🌲",
    palette: "forest",
    price: "450.000",
    unit: "malam",
    cap: "2 orang",
    tagline: "Cabin mini di tengah hutan pinus.",
    description: "Cabin kayu minimalis buat dua orang. Privat, quiet, cocok buat nulis atau just disconnect. Ada hammock dan fire pit kecil.",
    amenities: ["Cabin kayu", "Double bed", "Heater", "Fire pit", "Breakfast box", "Wi-Fi (ada tapi lemah)"],
    availability: "Available · weekdays & weekend",
    tag: null,
  },
];

// Common settings (Tweaks will mutate these)
const EJG_SETTINGS = /*EDITMODE-BEGIN*/{
  "showWhatsappFab": true,
  "playfulMode": true,
  "heroVariant": "stamp"
}/*EDITMODE-END*/;

const WHATSAPP = "6285117322207";

Object.assign(window, {
  UPCOMING_OPEN_TRIPS,
  PRIVATE_DESTINATIONS,
  GLAMPINGS,
  EJG_SETTINGS,
  WHATSAPP,
});
