// EH! JADI GA? — mobile web data

const WHATSAPP = "6281234567890";

const UPCOMING_OPEN_TRIPS = [
  {
    id: "ot-bromo-may",
    dest: "Bromo Sunrise",
    region: "Jawa Timur",
    month: "MEI", day: "24",
    start: "24 Mei", end: "25 Mei",
    duration: "2D1N",
    price: "850K",
    slots: 4, totalSlots: 12,
    tag: "LAST SLOTS",
    palette: "ink",
    emoji: "🌋",
    highlights: ["Sunrise Penanjakan", "Kawah Bromo naik jeep", "Padang Savana & Pasir Berbisik"],
    includes: ["Jeep tour 4x", "Breakfast + 1x lunch", "Homestay sharing", "Guide lokal", "Dokumentasi HP"],
  },
  {
    id: "ot-ijen-may",
    dest: "Ijen Blue Fire",
    region: "Jawa Timur",
    month: "MEI", day: "31",
    start: "31 Mei", end: "1 Jun",
    duration: "2D1N",
    price: "1.1jt",
    slots: 7, totalSlots: 12,
    palette: "dusk",
    emoji: "🔥",
    highlights: ["Pendakian midnight", "Blue fire view", "Sunrise di kawah"],
    includes: ["Transport AC", "Tiket kawah + gas mask", "Guide pendakian", "Warung kopi di basecamp"],
  },
  {
    id: "ot-sewu-jun",
    dest: "Tumpak Sewu + Goa Tetes",
    region: "Lumajang",
    month: "JUN", day: "14",
    start: "14 Jun", end: "15 Jun",
    duration: "2D1N",
    price: "950K",
    slots: 9, totalSlots: 14,
    palette: "forest",
    emoji: "🏞️",
    highlights: ["Hike ke dasar Tumpak Sewu", "Goa Tetes", "Sunset di viewpoint"],
    includes: ["Transport", "Guide + local porter", "Makan 3x", "Homestay"],
  },
  {
    id: "ot-kelud-jun",
    dest: "Kelud Crater Hunt",
    region: "Kediri",
    month: "JUN", day: "28",
    start: "28 Jun", end: "29 Jun",
    duration: "2D1N",
    price: "780K",
    slots: 2, totalSlots: 10,
    tag: "ALMOST FULL",
    palette: "warm",
    emoji: "⛰️",
    highlights: ["Crater hunt pagi", "Air panas Kelud", "Sunset Bukit Kura-kura"],
    includes: ["Transport", "Tiket + guide", "Makan 3x", "Penginapan"],
  },
  {
    id: "ot-gili-jul",
    dest: "Gili Labak Snorkeling",
    region: "Madura",
    month: "JUL", day: "12",
    start: "12 Jul", end: "13 Jul",
    duration: "2D1N",
    price: "1.2jt",
    slots: 11, totalSlots: 14,
    palette: "sky",
    emoji: "🏝️",
    highlights: ["Snorkeling 3 spot", "Sunset di pier", "Nginep di pulau"],
    includes: ["Transport + boat", "Snorkel gear", "Makan 3x", "Tenda share"],
  },
];

const PRIVATE_DESTINATIONS = [
  { id: "pronojiwo", name: "Pronojiwo", sub: "Tumpak Sewu, Goa Tetes, Kapas Biru", emoji: "💧" },
  { id: "bromo",     name: "Bromo",     sub: "Savana, Kawah, Sunrise", emoji: "🌋" },
  { id: "ijen",      name: "Ijen",      sub: "Blue fire + kawah belerang", emoji: "🔥" },
  { id: "malang",    name: "Malang",    sub: "Kota kreatif, kopi, kuliner", emoji: "☕" },
  { id: "kelud",     name: "Kelud",     sub: "Crater + hot spring", emoji: "⛰️" },
  { id: "custom",    name: "Bikin sendiri", sub: "Racik route custom", emoji: "✏️" },
];

const GLAMPINGS = [
  {
    id: "gl-senggani",
    name: "Jurang Senggani",
    location: "Tulungagung, Jawa Timur",
    palette: "forest",
    emoji: "🏕️",
    tag: "SIGNATURE",
    price: "650K",
    unit: "malam",
    cap: "2–4 org / tent",
    availability: "Buka setiap hari",
    tagline: "Kemah, tapi tetep wangi pas bangun.",
    description: "Tent premium di tengah pinus Tulungagung. Tempat tidur beneran, listrik, air panas. Malam ada campfire & BBQ; pagi ada kabut tipis di atas lembah. Pas buat yang pengen ngerasain outdoor tanpa ribet urus tenda.",
    amenities: ["Tempat tidur queen", "Kamar mandi air panas", "Campfire + BBQ set", "Breakfast lokal", "Wifi di common area"],
  },
  {
    id: "gl-batu",
    name: "Kaliwatu Highland",
    location: "Kota Batu, Jawa Timur",
    palette: "sky",
    emoji: "🌄",
    price: "890K",
    unit: "malam",
    cap: "2–6 org / dome",
    availability: "Buka setiap hari",
    tagline: "Dome kaca, view kota Malang di kaki.",
    description: "Transparent dome di punggung Gunung Banyak. Bintang full di atas kepala, city light Malang di bawah. Ada balkon untuk sunrise, dan hot tub outdoor.",
    amenities: ["Dome kaca private", "Hot tub outdoor", "Heater elektrik", "Breakfast + welcome drink", "Akses private deck"],
  },
  {
    id: "gl-tete",
    name: "Tete Cabin",
    location: "Pacet, Mojokerto",
    palette: "warm",
    emoji: "🛖",
    tag: "BARU",
    price: "720K",
    unit: "malam",
    cap: "2–3 org / cabin",
    availability: "Closed Rabu",
    tagline: "Cabin kayu mini, sunset ke arah Welirang.",
    description: "Cabin kayu pinus di kaki Gunung Welirang. Kecil, hangat, punya teras + hammock. Cocok buat couple atau solo stay biar bisa deep work dari hutan.",
    amenities: ["Cabin kayu private", "Heating pad & selimut wol", "Dapur mini + kompor", "Breakfast delivery", "Akses trail pagi"],
  },
];

Object.assign(window, { WHATSAPP, UPCOMING_OPEN_TRIPS, PRIVATE_DESTINATIONS, GLAMPINGS });
