// Mock data for the UI kit
const TRIPS = [
  {
    id: "bromo",
    title: "Sunrise Bromo & Savana Teletubbies",
    region: "Jawa Timur",
    kind: "Open trip",
    emoji: "🌋",
    palette: "",
    tag: "🔥 Popular",
    duration: "3H2M",
    date: "17 Mei",
    price: "850K",
    meta: "Jeep, hotel, makan, guide — termasuk semua.",
    slots: "Tinggal 4 slot",
    description: "3 hari 2 malam keliling Bromo klasik. Jeep sunrise, savana, pasir berbisik, plus pit stop ke Kawah Ijen kalau cuaca oke.",
    includes: ["Jeep 4x4 sharing", "Hotel 2 malam dekat Cemoro Lawang", "3x makan + 2x sarapan", "Guide lokal bahasa Indo/EN", "Masuk kawasan + parkir", "Asuransi perjalanan"],
    notExcludes: ["Tiket pesawat ke Surabaya", "Pengeluaran pribadi"],
    itinerary: [
      { day: 1, title: "Surabaya → Cemoro Lawang", desc: "Jemput pagi di stasiun/bandara, 4 jam ke penginapan, check-in, sore eksplor desa." },
      { day: 2, title: "Sunrise Bromo day", desc: "2AM jeep sunrise di Penanjakan, savana, pasir berbisik, kawah. Balik hotel, istirahat." },
      { day: 3, title: "Pulang via Madakaripura", desc: "Air terjun tersembunyi pagi-pagi, lunch, antar balik ke Surabaya sore." },
    ],
  },
  {
    id: "komodo",
    title: "Open Trip Komodo 3H2M Phinisi",
    region: "NTT",
    kind: "Open trip",
    emoji: "🐉",
    palette: "sky",
    tag: "Last slots",
    duration: "3H2M",
    date: "24 Mei",
    price: "2.4jt",
    meta: "Phinisi + snorkeling + Padar + Pink Beach.",
    slots: "Tinggal 2 slot",
  },
  {
    id: "dieng",
    title: "Dieng Plateau Golden Sunrise",
    region: "Jawa Tengah",
    kind: "Private trip",
    emoji: "⛰️",
    palette: "warm",
    tag: null,
    duration: "2H1M",
    date: "Custom",
    price: "1.2jt",
    meta: "Private jeep. Telaga Warna, Sikunir, candi.",
  },
  {
    id: "nusa",
    title: "Nusa Penida Instagram Tour",
    region: "Bali",
    kind: "Open trip",
    emoji: "🏝️",
    palette: "sky",
    tag: "🔥 Popular",
    duration: "2H1M",
    date: "31 Mei",
    price: "1.1jt",
    meta: "Kelingking, Broken, Angel's Billabong.",
  },
];

const GLAMPS = [
  { id: "gl1", title: "Pinggir Sawah Tent", location: "Pacet, Jawa Timur", price: "650K", emoji: "🏕️" },
  { id: "gl2", title: "Bukit Bintang Dome", location: "Lembang, Jawa Barat", price: "890K", emoji: "⛺" },
  { id: "gl3", title: "Pantai Senja Cabin", location: "Pangandaran", price: "1.1jt", emoji: "🏖️" },
  { id: "gl4", title: "Hutan Pinus Treehouse", location: "Bandung", price: "750K", emoji: "🌲" },
];

Object.assign(window, { TRIPS, GLAMPS });
