export const WHATSAPP = "6285117322207";

export const UPCOMING_OPEN_TRIPS = [
  {
    id: "ot-bromo-may",
    dest: "Bromo Sunrise",
    region: "Jawa Timur",
    month: "MEI", day: "24",
    start: "24 Mei", end: "25 Mei",
    duration: "2D1N",
    price: "850K", priceNum: 850_000,
    slots: 4, totalSlots: 12,
    tag: "LAST SLOTS",
    palette: "ink",
    emoji: "🌋",
    description: "Sunrise dari Penanjakan yang ikonik — tapi kita lakuin dengan bener. Jeep 4x buat ke kawah, padang savana yang luas banget, dan penginapan lokal yang bikin ngerasa lebih otentik dari sekadar tour biasa. Ini bukan sekadar foto sunrise — ini pengalaman Bromo yang sesungguhnya.",
    highlights: ["Sunrise Penanjakan", "Kawah Bromo naik jeep", "Padang Savana & Pasir Berbisik"],
    includes: ["Jeep tour 4x", "Breakfast + 1x lunch", "Homestay sharing", "Guide lokal", "Dokumentasi HP"],
    gallery: ["Sunrise dari Penanjakan", "Kawah & jeep tour", "Savana pagi hari", "Homestay malam"],
  },
  {
    id: "ot-ijen-may",
    dest: "Ijen Blue Fire",
    region: "Jawa Timur",
    month: "MEI", day: "31",
    start: "31 Mei", end: "1 Jun",
    duration: "2D1N",
    price: "1.1jt", priceNum: 1_100_000,
    slots: 7, totalSlots: 12,
    palette: "dusk",
    emoji: "🔥",
    description: "Satu-satunya blue fire alami di dunia yang bisa dikunjungi. Kita berangkat tengah malam, mendaki dalam gelap, dan menyaksikan api biru yang keluar dari retakan kawah. Pengalaman yang susah dijelaskan pakai kata — harus dirasain sendiri.",
    highlights: ["Pendakian midnight", "Blue fire view", "Sunrise di kawah"],
    includes: ["Transport AC", "Tiket kawah + gas mask", "Guide pendakian", "Warung kopi di basecamp"],
    gallery: ["Blue fire tengah malam", "Kawah belerang pagi", "Sunrise di bibir kawah", "Trek menuju puncak"],
  },
  {
    id: "ot-sewu-jun",
    dest: "Tumpak Sewu + Goa Tetes",
    region: "Lumajang",
    month: "JUN", day: "14",
    start: "14 Jun", end: "15 Jun",
    duration: "2D1N",
    price: "950K", priceNum: 950_000,
    slots: 9, totalSlots: 14,
    palette: "forest",
    emoji: "🏞️",
    description: "Air terjun bertingkat yang foto-fotonya sering viral — tapi jarang yang beneran turun ke dasarnya. Kita turun. Dari sana kita lanjut ke Goa Tetes yang stalaktitnya masih asri. Dua spot, satu hari, banyak cerita.",
    highlights: ["Hike ke dasar Tumpak Sewu", "Goa Tetes", "Sunset di viewpoint"],
    includes: ["Transport", "Guide + local porter", "Makan 3x", "Homestay"],
    gallery: ["Air terjun dari bawah", "Goa Tetes dalam", "Viewpoint sunset", "Trek hutan lebat"],
  },
  {
    id: "ot-kelud-jun",
    dest: "Kelud Crater Hunt",
    region: "Kediri",
    month: "JUN", day: "28",
    start: "28 Jun", end: "29 Jun",
    duration: "2D1N",
    price: "780K", priceNum: 780_000,
    slots: 2, totalSlots: 10,
    tag: "ALMOST FULL",
    palette: "warm",
    emoji: "⛰️",
    description: "Kawah yang lahir ulang pasca erupsi 2014. Danau toska di tengah kawah, air panas alami yang beneran panas, dan bukit sunset yang masih sepi dari turis. Kelud itu Bromo-nya orang yang udah bosen rame — tenang, tapi sama indahnya.",
    highlights: ["Crater hunt pagi", "Air panas Kelud", "Sunset Bukit Kura-kura"],
    includes: ["Transport", "Tiket + guide", "Makan 3x", "Penginapan"],
    gallery: ["Danau kawah toska", "Air panas alami", "Sunset Bukit Kura-kura", "Perkebunan lereng"],
  },
  {
    id: "ot-gili-jul",
    dest: "Gili Labak Snorkeling",
    region: "Madura",
    month: "JUL", day: "12",
    start: "12 Jul", end: "13 Jul",
    duration: "2D1N",
    price: "1.2jt", priceNum: 1_200_000,
    slots: 11, totalSlots: 14,
    palette: "sky",
    emoji: "🏝️",
    description: "Pulau kecil di sisi Madura yang airnya jernih kayak kaca. Tiga spot snorkeling, ikan warna-warni, dan tidur di tenda tepat di pinggir pantai sambil denger suara ombak. Gak ada sinyal yang bagus — dan itu justru yang bikin trip ini jadi bagus.",
    highlights: ["Snorkeling 3 spot", "Sunset di pier", "Nginep di pulau"],
    includes: ["Transport + boat", "Snorkel gear", "Makan 3x", "Tenda share"],
    gallery: ["Terumbu karang jernih", "Sunset di pier kayu", "Tenda di tepi pantai", "Ikan warna-warni"],
  },
];

export const OPEN_TRIP_ADDONS = [
  { id: 'single-supplement', label: 'Single Supplement', price: 150_000, desc: 'Kamar sendiri, tidak sharing' },
  { id: 'hotel-upgrade', label: 'Hotel Upgrade', price: 300_000, desc: 'Upgrade homestay ke hotel bintang 3' },
  { id: 'foto-pro', label: 'Dokumentasi Pro', price: 200_000, desc: 'Fotografer trip + edit basic' },
  { id: 'airport-transfer', label: 'Airport Transfer', price: 100_000, desc: 'Jemput/antar bandara' },
];

export const PRIVATE_DESTINATIONS = [
  {
    id: "pronojiwo",
    name: "Pronojiwo",
    region: "Lumajang, Jawa Timur",
    sub: "Tumpak Sewu, Goa Tetes, Kapas Biru",
    emoji: "💧",
    palette: "forest",
    description: "Kawasan tersembunyi di kaki Semeru. Air terjun bertingkat, goa kristal, dan sungai biru yang viral tapi tetap sepi. Cocok buat yang cari pengalaman di luar biasanya.",
    highlights: ["Tumpak Sewu dari dasar", "Goa Tetes & stalaktit", "Kapas Biru swim spot", "Sunrise dari Pronojiwo"],
    durations: ["2D1N", "3D2N"],
    startingPrice: "1.8jt",
    pricePerPax: 1_800_000,
    gallery: ["Tumpak Sewu dari dasar", "Goa Tetes stalaktit", "Kapas Biru sungai biru", "Kabut pagi Pronojiwo"],
  },
  {
    id: "bromo",
    name: "Bromo",
    region: "Probolinggo, Jawa Timur",
    sub: "Savana, Kawah, Sunrise",
    emoji: "🌋",
    palette: "ink",
    description: "Jeep, savana, kawah belerang. Sunrise Penanjakan yang bikin speechless. Lautan pasir yang bikin ngerasa kecil banget. Bromo selalu worth it.",
    highlights: ["Sunrise Penanjakan", "Jeep ke kawah Bromo", "Savana & Pasir Berbisik", "Bukit Teletubbies"],
    durations: ["2D1N", "3D2N", "4D3N"],
    startingPrice: "1.5jt",
    pricePerPax: 1_500_000,
    gallery: ["Sunrise lautan awan", "Jeep di lautan pasir", "Kawah dari dekat", "Savana & Bukit Teletubbies"],
  },
  {
    id: "ijen",
    name: "Ijen",
    region: "Banyuwangi, Jawa Timur",
    sub: "Blue fire + kawah belerang",
    emoji: "🔥",
    palette: "dusk",
    description: "Satu-satunya blue fire alami di dunia. Pendakian tengah malam, sunrise di pinggir kawah, terus nyebrang ke Bali. Intense, tapi gak ada duanya.",
    highlights: ["Blue fire midnight hike", "Sunrise kawah Ijen", "Turquoise acid lake view", "Lintas ke Bali (opsional)"],
    durations: ["2D1N", "3D2N"],
    startingPrice: "1.6jt",
    pricePerPax: 1_600_000,
    gallery: ["Blue fire di retakan", "Danau asam toska", "Sunrise bibir kawah", "Penambang belerang lokal"],
  },
  {
    id: "malang",
    name: "Malang",
    region: "Malang, Jawa Timur",
    sub: "Kota kreatif, kopi, kuliner",
    emoji: "☕",
    palette: "warm",
    description: "Bukan cuma foto-fotoan. Malang punya café tersembunyi, galeri lokal, dan food scene yang serius underrated. Kota yang nyaman buat jalan pelan-pelan.",
    highlights: ["Coffee crawl & café lokal", "Museum & galeri tersembunyi", "Kuliner non-tourist trap", "Day trip ke Coban Rondo"],
    durations: ["2D1N", "3D2N", "4D3N"],
    startingPrice: "1.2jt",
    pricePerPax: 1_200_000,
    gallery: ["Café lokal Malang", "Street art Kayutangan", "Coban Rondo waterfall", "Kuliner pasar malam"],
  },
  {
    id: "kelud",
    name: "Kelud",
    region: "Kediri, Jawa Timur",
    sub: "Crater + hot spring",
    emoji: "⛰️",
    palette: "warm",
    description: "Kawah yang lahir ulang pasca erupsi 2014. Sekarang ada danau hijau toska, air panas alami, dan bukit sunset yang masih sepi dari turis.",
    highlights: ["Kawah danau toska", "Air panas Kelud alami", "Sunset Bukit Kura-kura", "Perkebunan kopi lereng gunung"],
    durations: ["2D1N", "3D2N"],
    startingPrice: "1.3jt",
    pricePerPax: 1_300_000,
    gallery: ["Danau kawah toska", "Air panas alami", "Sunset Bukit Kura-kura", "Kebun kopi lereng gunung"],
  },
  {
    id: "custom",
    name: "Bikin sendiri",
    region: "Sesuai request",
    sub: "Racik route custom",
    emoji: "✏️",
    palette: "ink",
    description: "Ada destinasi yang pengen banget lo datengin? Kita bantu wujudkan. Dari Semeru sampai Raja Ampat, dari itinerary santai sampai yang ekstrem — cerita aja dulu.",
    highlights: ["Route custom sesuai keinginan", "Konsultasi gratis via WA", "Quote dalam 1×24 jam", "Bisa kombinasi multi-dest"],
    durations: ["Fleksibel"],
    startingPrice: "Sesuai itinerary",
    pricePerPax: null,
    gallery: ["Konsultasi route", "Itinerary custom", "Destinasi pilihan", "Tim planning"],
  },
];

const GLAMPING_ADDONS = [
  { id: 'bbq', label: 'BBQ Set', price: 150_000, desc: 'Peralatan BBQ lengkap untuk 4 org' },
  { id: 'birthday-cake', label: 'Birthday Cake', price: 200_000, desc: 'Kue custom + lilin + dekorasi' },
  { id: 'foto', label: 'Dokumentasi Pro', price: 300_000, desc: 'Sesi foto 1 jam + basic editing' },
  { id: 'extra-breakfast', label: 'Extra Breakfast', price: 45_000, desc: 'Per orang tambahan' },
  { id: 'bouquet', label: 'Bouquet Bunga', price: 150_000, desc: 'Untuk pasangan / anniversary' },
];

export const GLAMPINGS = [
  {
    id: "gl-senggani",
    name: "Jurang Senggani",
    location: "Tulungagung, Jawa Timur",
    palette: "forest",
    emoji: "🏕️",
    tag: "SIGNATURE",
    price: "650K", pricePerNight: 650_000,
    unit: "malam",
    cap: "2–4 org / tent",
    availability: "Buka setiap hari",
    tagline: "Tidur di alam, kasurnya beneran.",
    description: "Tent premium di tengah pinus Tulungagung. Tempat tidur beneran, listrik, air panas. Malam ada campfire & BBQ; pagi ada kabut tipis di atas lembah. Pas buat yang pengen ngerasain outdoor tanpa ribet urus tenda.",
    amenities: ["Tempat tidur queen", "Kamar mandi air panas", "Campfire + BBQ set", "Breakfast lokal", "Wifi di common area"],
    gallery: ["Tent di tengah pinus", "Campfire malam", "Kabut pagi lembah", "Sarapan outdoor"],
    addons: GLAMPING_ADDONS,
  },
  {
    id: "gl-batu",
    name: "Kaliwatu Highland",
    location: "Kota Batu, Jawa Timur",
    palette: "sky",
    emoji: "🌄",
    price: "890K", pricePerNight: 890_000,
    unit: "malam",
    cap: "2–6 org / dome",
    availability: "Buka setiap hari",
    tagline: "Dome kaca, view kota Malang di kaki.",
    description: "Transparent dome di punggung Gunung Banyak. Bintang full di atas kepala, city light Malang di bawah. Ada balkon untuk sunrise, dan hot tub outdoor.",
    amenities: ["Dome kaca private", "Hot tub outdoor", "Heater elektrik", "Breakfast + welcome drink", "Akses private deck"],
    gallery: ["Dome kaca malam", "City light dari balkon", "Hot tub outdoor", "Sunrise dari deck"],
    addons: GLAMPING_ADDONS,
  },
  {
    id: "gl-tete",
    name: "Tete Cabin",
    location: "Pacet, Mojokerto",
    palette: "warm",
    emoji: "🛖",
    tag: "BARU",
    price: "720K", pricePerNight: 720_000,
    unit: "malam",
    cap: "2–3 org / cabin",
    availability: "Closed Rabu",
    tagline: "Cabin kayu mini, sunset ke arah Welirang.",
    description: "Cabin kayu pinus di kaki Gunung Welirang. Kecil, hangat, punya teras + hammock. Cocok buat couple atau solo stay biar bisa deep work dari hutan.",
    amenities: ["Cabin kayu private", "Heating pad & selimut wol", "Dapur mini + kompor", "Breakfast delivery", "Akses trail pagi"],
    gallery: ["Cabin kayu dari depan", "Teras & hammock", "Sunset ke Welirang", "Interior cabin hangat"],
    addons: GLAMPING_ADDONS,
  },
];

export const SPECIAL_EVENTS = [
  {
    id: "ev-bromo-solstice",
    name: "Bromo Solstice Night",
    subtitle: "Satu malam penuh bintang sebelum sunrise paling epic.",
    date: "21 Jun", dateEnd: "22 Jun",
    year: "2026",
    venue: "Bromo, Jawa Timur",
    emoji: "🌌",
    palette: "ink",
    tag: "COMING SOON",
    description: "Bukan sekadar open trip biasa. Bromo Solstice Night adalah malam khusus di mana kita bakar api unggun di lautan pasir, dengerin live acoustic dari musisi lokal, dan tunggu sunrise terpanjang dalam setahun dari Penanjakan. Limited slot — karena kita mau ini intim dan beneran berasa.",
    highlights: [
      "Campfire di Lautan Pasir Bromo",
      "Live acoustic session tengah malam",
      "Sunrise prioritas dari Penanjakan",
      "Jeep 4x tour ke kawah pagi hari",
      "Sarapan bersama di atas lautan awan",
    ],
    includes: ["Transport AC Surabaya–Bromo PP", "Jeep 4x2 tour", "Makan 3x", "Penginapan sharing", "Live music & campfire setup", "Guide + dokumentasi HP"],
    tickets: [
      { id: "earlybird", label: "Early Bird", price: 1_200_000, desc: "Akses semua kegiatan, tenda sharing, makan 3x. Hanya 10 slot.", slots: 10 },
      { id: "regular",   label: "Regular",    price: 1_500_000, desc: "Akses semua kegiatan, tenda sharing, makan 3x.", slots: 20 },
      { id: "vip",       label: "VIP",        price: 2_200_000, desc: "Tenda private, welcome kit, makan 4x, priority sunrise spot, meet & greet musisi.", slots: 6 },
    ],
  },
  {
    id: "ev-ijen-midnight",
    name: "Ijen Midnight Run",
    subtitle: "Midnight hike bareng, blue fire bareng.",
    date: "19 Jul", dateEnd: "20 Jul",
    year: "2026",
    venue: "Ijen, Banyuwangi",
    emoji: "🔵",
    palette: "dusk",
    tag: "OPEN",
    description: "Ini bukan hiking biasa. Ijen Midnight Run adalah event sosial — kita kumpul di basecamp jam 11 malam, jalan bareng, saling semangatin di jalur gelap, dan menyaksikan api biru bersama. Ada fotografer profesional yang ikut mendokumentasikan setiap momen. Pulang bawa foto, bawa cerita.",
    highlights: [
      "Midnight group hike mulai 23.00",
      "Blue fire view bareng komunitas",
      "Fotografer pro sepanjang jalur",
      "Sunrise di bibir kawah",
      "Breakfast + sesi foto group",
    ],
    includes: ["Transport AC Surabaya–Banyuwangi PP", "Tiket kawah + gas mask", "Guide pendakian", "Fotografer + 10 foto edited", "Breakfast di basecamp"],
    tickets: [
      { id: "hiker",      label: "Hiker",           price: 950_000,   desc: "Akses penuh event + semua include standar.", slots: 30 },
      { id: "hiker-foto", label: "Hiker + Foto Pack", price: 1_350_000, desc: "Semua include + 20 foto edited + 1 print A4.", slots: 15 },
    ],
  },
];
